## Append samples of your project ##
resources:
- paas_v1alpha1_postgrescluster.yaml
- paas_v1alpha1_valkeycluster.yaml
- paas_v1alpha1_grafanainstance.yaml
- paas_v1alpha1_mariadbcluster.yaml
- paas_v1alpha1_rabbitmqcluster.yaml
- paas_v1alpha1_prometheusinstance.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
