apiVersion: paas.example.com/v1alpha1
kind: GrafanaInstance
metadata:
  labels:
    app.kubernetes.io/name: paas-operator
    app.kubernetes.io/managed-by: kustomize
  name: grafanainstance-sample
spec:
  replicas: 1
  persistence:
    size: 1Gi
